variables:
  GIT_SUBMODULE_STRATEGY: recursive

wally_release_files:
  image: greenaddress/wallycore@sha256:eb0bdb6119f40df02bbc3cd38ba64ea1c3de64c2d065e61a0447986068fca6be
  artifacts:
    expire_in: 7 days
    name: wallycore-bindings
    when: on_success
    paths:
    - dist/*
  tags:
    - ga
  script:
    - python3 -m build
    - virtualenv -p python3 .smoketest
    - source .smoketest/bin/activate
    - pip install --find-links=./dist wallycore
    - python -c "import wallycore as w; assert w.hex_from_bytes(w.hex_to_bytes('ff')) == 'ff'"
    - deactivate
    - rm -rf .smoketest
    - rm dist/*.whl
    - mv dist wally_dist
    - ./tools/build_android_libraries.sh
    - mv release wallycore-android-jni
    - tar czf wally_dist/wallycore-android-jni.tar.gz --remove-files wallycore-android-jni
    - source /opt/emsdk/emsdk_env.sh
    - tools/build_wasm.sh
    - cd dist
    - tar czf wallycore-wasm.tar.gz --remove-files wallycore.html wallycore.js wallycore.wasm
    - cd ..
    - sphinx-build -b html -a -c docs/source docs/source docs/build/html
    - cd docs/build
    - tar czf ../../wally_dist/apidocs.tar.gz html/
    - cd ../..
    - mv wally_dist/* dist/
    - rmdir wally_dist

build_mingw_static:
  image: greenaddress/wallycore@sha256:eb0bdb6119f40df02bbc3cd38ba64ea1c3de64c2d065e61a0447986068fca6be
  tags:
    - ga
  script:
    - ./tools/cleanup.sh && ./tools/autogen.sh
    - CC=x86_64-w64-mingw32-gcc ./configure --host=x86_64-w64-mingw32 --disable-swig-python --disable-swig-java --disable-shared --enable-static
    - make -j $(($(grep ^processor /proc/cpuinfo | wc -l) / 2))
